# Generated by Django 5.2.5 on 2025-08-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_new', models.BooleanField(default=True, help_text='檢查使用者是否為第一次使用 App 並需要進行初次測試')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('psid', models.AutoField(primary_key=True, serialize=False)),
                ('input_mp3_path', models.CharField(help_text='ASR 輸入的 MP3 路徑', max_length=255)),
                ('output_txt', models.CharField(help_text='ASR 的輸出文字', max_length=255)),
                ('language', models.CharField(choices=[('EN', 'English'), ('CH', 'Chinese')], max_length=2)),
                ('target_word', models.CharField(max_length=255)),
                ('diffi_level', models.CharField(help_text='難度等級', max_length=20)),
                ('error_rate', models.FloatField()),
                ('full_log', models.TextField(help_text='完整的輸出日誌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgressSummary',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('phoneme', models.CharField(help_text='使用者的錯誤音素', max_length=255)),
                ('total_atmp', models.IntegerField(default=0, help_text='該音素的總嘗試次數')),
                ('err_amount', models.IntegerField(default=0, help_text='該音素的錯誤次數')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'language', 'phoneme')},
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('sug_lvl', models.CharField(help_text='基於初次測試結果的建議難度等級', max_length=20)),
                ('cur_lvl', models.CharField(help_text='使用者自己選擇的當前難度等級', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('cur_word', models.CharField(help_text='使用者當前的目標單詞', max_length=255)),
                ('cur_err', models.CharField(help_text='使用者當前的錯誤音素', max_length=255)),
                ('cur_log', models.TextField(help_text='使用者當前的完整結果日誌')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'language')},
            },
        ),
    ]
