# Generated by Django 5.2.5 on 2025-08-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='input_mp3_path',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='input_audio_path',
            field=models.CharField(default='no_audio.mp3', max_length=255),
        ),
    ]
