# Generated by Django 5.2.5 on 2025-08-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_practicesession_input_mp3_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicesession',
            old_name='output_text',
            new_name='asr_output',
        ),
    ]
